import { defineConfig } from "tsdown";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    auth: "src/auth/index.ts",
    user: "src/user/index.ts",
    admin: "src/admin/index.ts",
    business: "src/business/index.ts",
    patient: "src/patient/index.ts",
    doctor: "src/doctor/index.ts",
    availability: "src/availability/index.ts",
    appointment: "src/appointment/index.ts",
    chat: "src/chat/index.ts",
    payment: "src/payment/index.ts",
    campaign: "src/campaign/index.ts",
    audit: "src/audit/index.ts",
    traffic: "src/traffic/index.ts",
    contact: "src/contact/index.ts",
    newsletter: "src/newsletter/index.ts",
    dashboard: "src/dashboard/index.ts",
    media: "src/media/index.ts",
    notification: "src/notification/index.ts",
    staff: "src/staff/index.ts",
    product: "src/product/index.ts",
    order: "src/order/index.ts",
  },
  outDir: "dist",
  format: ["esm"],
  target: "es2024",
  sourcemap: true,
  clean: true,
  dts: true,
  minify: false,
  deps: {
    neverBundle: [
      "@workspace/shared",
      "@workspace/db",
      "zod",
      "nestjs-zod",
      "react",
      "@types/react",
      "@tabler/icons-react",
    ],
  },
});
